name: 🚀 Deploy website on push
on:
  workflow_dispatch:
  push:
    branches:
      - prod

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.19.1

      - name: 📦 Compile
        run: make gen
        
      - name: 📦 List Files
        run: ls -hal

      - name: 📂 Sync files
        uses: Creepios/sftp-action@v1.0.4
        with:
          host: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: /home/runner/work/xenonlabs-website/xenonlabs-website/.output/public
          remotePath: /var/lib/docker/volumes/Web/_data
